### ISSUE TITLE
Problems in `evaluate` and `load`

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#14]
### 1. Hanging in the following test case

```shell
echo 'cr char ^ parse  s" source-id . blk @ . " evaluate ^ 1 buffer swap cmove 1 load bye' | ./post4 -b tmp.blk
```

Actual output (after twice Ctrl+C):
```output
^C-1 1 -28 thrown
^C-28 thrown
```

Expected output:
```output
-1 0
```

### 2. Problem in `load`

https://github.com/SirWumpus/post4/blob/5f5bec82d8b2cc8ac69fdcf56376fde0b3049969/src/post4.p4#L1897

`load ( i*x u.block -- j*x ) `  can consume and leave items on the data stack. So, it's incorrect to keep previous value of `blk` on the data stack. The return stack can be used for that. Also, the _input source specification_ (that includes `blk`) shall be restored if an exception was thrown. A simple way to do it in this case is to catch the exception, restore `blk`, and then rethrow the exception:
```forth
: LOAD ( i*x u -- j*x )  BLK @ >R  DUP BLK !  BLOCK 1024  ['] EVALUATE CATCH ( ior|0 )  R> BLK !  THROW ; 
```

### 3. Problem in `evaluate`

If the Block word set is provided, `evaluate` must set zero in `blk` ([7.6.1.1360](https://forth-standard.org/standard/block/EVALUATE)). So, it's incorrect to use `evaluate` to implement `load`.

At the moment, `evaluate` in post4 does not change `blk`. So the above `load` would be correct, while `evaluate` is incorrect.

A possible solution is to later redefine `evaluate` as:
```forth
: EVALUATE ( i*x c-addr u -- j*x )  BLK @ >R  0 BLK !  ['] EVALUATE CATCH  R> BLK !  THROW ;
```

Or, introduce another common factor for both `load` and `evaluate`.

**Comment by SirWumpus** [comment]
Ok.  The last two points and the proposed seem straight forward (famous last words I'm sure).

Since Post4 has extra words `BLOCK-OPEN` and `BLOCK-CLOSE` I've been able to create the start to a Block test suite.  In the case of 1. above it narrows down to `LOAD` and looks to be a nested call issue WRT `p4EvalString()`, which I'm looking into.

@ruv Sidebar question: In your failure example, is there any reason you don't `BLANK` the buffer first?  (I tested that and it made no difference.)  How do other Forths or the standard handle dealing with random octets after the copied text.  There does not seem to be any statement about `LOAD` parsing a partial text block followed by garbage (all null, all blanks, random junk).

**Comment by ruv** [comment]
>  changes seem straight forward (famous last words I'm sure).

🤣

>  In your 1. failure example, is there any reason you don't `BLANK` the buffer first? 

It's my omission.  The spec [says](https://forth-standard.org/standard/block/BUFFER) "The contents of the block are unspecified".  By coincidence, the block contained null characters only.

A correct program:
```forth
1 buffer dup 1024 blank ( a-addr )
char ^ parse  cr s" source-id . blk @ . " evaluate ^ rot swap cmove update
1 load
```

**Comment by SirWumpus** [comment]
> ... narrows down to `LOAD` and looks to be a nested call issue WRT p4EvalString(), which I'm looking into.

I've found the issue with input handling in `p4Refill()` and `p4Accept()`.  Essentially a one line change to break the infinite loop.
