### ISSUE TITLE
Nesting LOAD may not work.

### ISSUE THREAD

**Issue by SirWumpus** [SirWumpus/post4#16]
Forth 2019 section 7.3.3 Parsing paragraph 3;

> A program may switch the input source to a block by using `LOAD` or `THRU`. Input sources may be nested
using LOAD and EVALUATE in any order.

* Add test to verify that nested `LOAD` work correctly.
* Add test that nested `EVALUATE` work correctly.
* Add tests nesting `LOAD` and `EVALUATE` behave.

The main concern here is that Post4 uses a single permanent BLOCK buffer and nested `LOAD` will not correctly continue evaluation as the each `LOAD` pops.  `EVALUATE` should already correctly nest, but double check.

**Comment by SirWumpus** [comment]
@ruv If nesting must be supported to at least 8 levels:

11.3.3 Input source
> Input with INCLUDED, INCLUDE-FILE, LOAD and EVALUATE shall be nestable in any order to at least eight levels.

Does that imply the need to support a minimum of 8 source blocks (8KB) (which seems expensive for historical 8-bit Forths with 64 KB RAM).  Especially since section 7.4.1.3 Other system documentation `the number of blocks available for source text and data` appears to leave the number of blocks supported to the implementation.

**Comment by SirWumpus** [comment]
@ruv Nested `INCLUDE` family, `EVALUATE`, and `LOAD` should all work now.  My `LOAD` tests aren't fancy.  If you have more interesting ones to add, that would be great.  Closing.

**Comment by ruv** [comment]
> Does that imply the need for `LOAD` to support a minimum of 8 source blocks (8KB) (which seems expensive for historical 8-bit Forths with 64 KB RAM).

No, because the system may reuse block buffers. Technically, the system can have only one block buffer. Moreover, this requirement did not exist in the time of that historical systems.

[Forth-83](https://www.complang.tuwien.ac.at/forth/fth83std/FORTH83.TXT) said: “Therefore the address of a block buffer returned by `BLOCK` or `BUFFER` becomes invalid during and after the execution of any word marked by the attribute **M** in the glossary or any words executing them”.  Also, Forth-83 did not provide any guarantees regarding the computed addresses withing the input buffer.

But since Forth-94 the standard provides some guarantees regarding the computed addresses in the input buffer and their contents (see [my interpretation](https://forth-standard.org/standard/block/EMPTY-BUFFERS#reply-1298)).  This creates the possibility for edge cases in which an implementation (a Forth system) can violate these guarantees due to some oversight.

Note: if some behavior of a Forth system is not _explicitly_ permitted by the standard and can be detected by a standard program, then that behavior is prohibited for the system.

-----

>  Especially since section 7.4.1.3 Other system documentation `the number of blocks available for source text and data` appears to leave the number of blocks supported up to the implementation.

This is about the total number of blocks available in the mass storage.

**Comment by ruv** [comment]
> since Forth-94 the standard provides some guarantees regarding the computed addresses in the input buffer and their contents 

Well, it seems, the [section 7.3.2](https://forth-standard.org/standard/block#subsection.7.3.2) removes these guarantees when the input source is a block.  It means, a program is very restricted if it does not depend on the input source kind (and does not have the corresponding environmental dependencies).

It would be better if the Forth system provided the same guarantees regardless of the input source kind.
