### ISSUE TITLE
`quit` inside an included file

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#54]
In post4/0.12.0,  `quit` behaves incorrectly in some cases.

Given the file `test-quit.fth`:
```forth
132 dup . cr quit cr 456 . cr
```
It is expected that it prints `132` and start REPL. The part "cr 456 . cr" should never get control.

When included from the shell command line, it behaves as expected:
```shell
post4 -i test-quit.fth
```

But when we load this file interactively (in REPL), it behaves incorrectly:
```log
include test-quit.fth
132
-9 thrown: invalid memory address

>>
>> ^
-9 thrown: invalid memory address
ok
```

**Comment by ruv** [comment]
If we pass this file as a script, the behavior is unexpected too:
```shell
post4 test-quit.fth
```
— it just prints "132" and terminates with exit status 0.

Does it mean that the user input device is equivalent to `/dev/null` in this case?

**Comment by SirWumpus** [comment]
* Expect to run and exit at EOF.
```shell
elf$ ./post4 <../test/data/quit0.p4 ; echo $?
132
0
elf$
```
* Expect to include a file and wait for user input:
```
elf$ ./post4 -i ../test/data/quit0.p4 ; echo $?
132
ok bye
0
elf$
```
* Expect to run program and exit at EOF:
```
elf$ ./post4 ../test/data/quit0.p4 ; echo $?
132
0
elf$
```
* Expect to enter REPL, accept user input,
```
elf$ ./post4
ok include ../test/data/quit0.p4
132

>>
>> ^
-9 thrown: invalid memory address
ok
```

I've tested HEAD, v0.12.0, and v0.11.0 and all fail case 4.   Case 1 & 3 read from C's `stdin`.

Case 2 reads the file before entering the REPL, which should be reading from a terminal, typically `STDIN_FILENO` (older versions will open `ctermid()`).

Not sure why case 4 generates SIGSEGV, but I'll debug it and find out.  Probably some issue switching input source.

**Comment by SirWumpus** [comment]
Ok. It appears to be a nesting issue at `_fa_include:` with `p4EvalFp()`.  `QUIT` wipes the return stack, so on return from `p4Evalfp()` the `ip` is loaded with a bogus address.  Essentially I need to do something similar to what I did for `EVALUATE`.  Its a clear bug.

**Comment by ruv** [comment]
> Case 1 & 3 read from C's `stdin`.
 
Ah, I see. `quit` reads the next line from the file. That's correct.

-----

> `QUIT` wipes the return stack, so on return from `p4Evalfp()` the `ip` is loaded with a bogus address.

BTW, it is not necessary to clear the return stack to depth 0. It is possible to leave some addresses on the return stack to provide the return address.

**Comment by SirWumpus** [comment]
> > `QUIT` wipes the return stack, so on return from `p4Evalfp()` the `ip` is loaded with a bogus address.
> 
> BTW, it is not necessary to clear the return stack to depth 0. It is possible to leave some addresses on the return stack to provide the return address.

Hmm.  Not sure I like that idea.  Anyway, I think it would be "cleaner" to avoid `p4EvalFp()` when interactive.  I'll need to have poke about to see which way is best.

**Comment by SirWumpus** [comment]
I really hate the definition of `QUIT` at times.  

It essentially behaves likes an NMI or `kill -9` since you're not allowed to `: QUIT -59 THROW ;` nor catch it in a manner similar to `ABORT`, which makes allocated memory and file handle clean-up next to impossible (unless you create some sort garbage collector which seem like overkill).  So repeated `QUIT` is likely to lead to memory and file-id leaks over time if applied regularly within words or nested `INCLUDE` files.  With block systems were/are the norm and the memory allocation word-set did not exist, `QUIT` was fine, since there were few resources to manage, however I think the behaviour of `QUIT` on modern systems just feels broken. 

(Just venting frustration.)

Using `QUIT` to terminate the current level of nesting might make more sense, but I can't turn back time and have this redefined.  So all I get to do is complain and huddle in a dark corner and pass gas.

**Comment by ruv** [comment]
> So repeated `QUIT` is likely to lead to memory and file-id leaks over time if applied regularly within words or nested `INCLUDE` files.

**It not allowed** for `QUIT` to close any files of free any memory blocks.  Nowadays `QUIT` is mainly used as a debugging tool. You can put it in any place of a program and get into the context of that place. And you expect the memory blocks and fileids to be valid for inspection.

Actually, your `QUIT` might even leave the return stack un-cleared, since the standard program/user cannot detect this.

**Comment by SirWumpus** [comment]
> **It not allowed** for `QUIT` to close any files of free any memory blocks. Nowadays `QUIT` is mainly used as a debugging tool. You can put it in any place of a program and get into the context of that place. And you expect the memory blocks and fileids to be valid for inspection.
> 
> Actually, your `QUIT` might even leave the return stack un-cleared, since the standard program/user cannot detect this.

Well my version does `Empty the return stack, ...` and try return the top level REPL.  As discussed above when the stdin is redirected or a program given, then it will stop, reset the input buffer and continue with the next line.  The `-i` case works because the files are processed separately in order of `-i` options and then enters interactive.  

```
elf$ cd post4/src
/home/achowe/git/com/snert/src/post4/src
elf$ ./post4 ../test/data/quit0.p4
132
ds
top-00 $0000000000000084
elf$
elf$ ./post4 <../test/data/quit0.p4
132
ds
top-00 $0000000000000084
elf$ 
```

If `QUIT` is intended more as a debugging tool, then you should *not* clear the return stack so that it can be examined too.  

Hmm.  More I think about it, a strict `QUIT` on the above case should also drop into the prompt.  Would be cool would be `STOP` and `RESUME`  to allow pause for debugging.  Hmm. (Mind wonders into an abyss.)

**Comment by ruv** [comment]
>  More I think about it, a strict `QUIT` on the above case should also drop into the prompt. 

It should be indicated in the prompt?  Or what do you mean?


> Would be cool would be `STOP` and `RESUME` to allow pause for debugging.

This can be implemented in a standard program using `accept` and `evaluate` in a loop.
For example:
```forth
false value v_resume
: resume ( -- ) true to v_resume source nip >in ! ;
: stop ( "ccc" -- )
  false to v_resume
  begin
    cr ." stack: " .s cr ." debug> "
    here 100 accept here swap ( sd.input )
    ['] evaluate catch ?dup if nip nip ." error: " . then
    v_resume
  until
;
```

**Comment by SirWumpus** [comment]
> > More I think about it, a strict `QUIT` on the above case should also drop into the prompt.
> 
> It should be indicated in the prompt? Or what do you mean?

`Drop into the prompt` ie. return to interactive input.

> > Would be cool would be `STOP` and `RESUME` to allow pause for debugging.
> 
> This can be implemented in a standard program using `accept` and `evaluate` in a loop. For example:

Of course it can.  Now why would I expect anything else? 😁

**Comment by SirWumpus** [comment]
Ok.  I think I have a fix for all cases...
```
elf$ ./post4 ../test/data/quit0.p4
132
ok
post4: ../test/data/quit0.p4: -56 thrown
elf$ ./post4 < ../test/data/quit0.p4
132
ds
top-00 $0000000000000084               \ I added `.s` on the next line to see when it hits.
elf$ ./post4 -i ../test/data/quit0.p4
132
ok quit
ok quit                                \ repeated interactive QUIT should not terminate.
ok
post4: ../test/data/quit0.p4: -56 thrown
elf$ ./post4
ok include ../test/data/quit0.p4
132
ok quit
ok quit
ok                                     \ EOF (^D) terminates the inner p4Repl()
ok                                     \ EOF (^D) terminates the top most p4Repl(). 
elf$
```
I'm going to sit on this a while till tomorrow, just in case I think of something else.

**Comment by SirWumpus** [comment]
Question:  Should `QUIT` which has an exception code be passed to `exit()`, exiting with non-zero to the shell?  Before now, any uncaught exception during runtime would be used as the exit code; `QUIT` was excluded result in zero on exit for an otherwise clean run.

**Comment by ruv** [comment]
>  Should `QUIT` which has an exception code be passed to `exit()`, exiting with non-zero to the shell?

I think, no. 

I see the following ways of the process termination from `quit`:
1. `bye` — exit status is zero.
2. `bye-status ( n -- )` — the exit status is _n_
3. End of the input source — the exit status is 0.
4. Ctrl+C (if supported) — the exit status is a nonzero.
5.. external kill — the exit status is a nonzero.

**Comment by SirWumpus** [comment]
I'm only really concerned about the case when EOF is reached (or typed ^D).  `BYE` and `BYE-CODE` are clearly defined and return an explicit exit status.

A user interrupt, SIGINT (^C), is an exception caught by Post4 and IMO should the program reach EOF (^D) then the exit status should be non-zero.  A quit signal SIGQUIT (^\\) I'm leaning to NOT being caught by Post4.

Similarly for `ABORT` or other exceptions during execution of an application (or interactive use) should return a non-zero exit status at EOF.  For example piping input `echo ABORT | post4`; I want to see a non-zero exit status because there was an exception at some point during the session.  So `echo no-such-word | post4` will result in -13 exception and a non-zero exit status.  `QUIT` is an exception too, with special behaviour, but still behaves like an exception.

See my comment on exit status : https://github.com/ForthHub/discussion/discussions/185#discussioncomment-11153759

If a program runs "clean" without any uncaught exceptions then EOF would result in zero (0) exit status.

Sidebutt:  I see you still really prefer I rename `bye-code` to `bye-status`.  I'm still thinking about it.

**Comment by ruv** [comment]
> should the program reach EOF (^D) then the exit status should be non-zero.

Do you mean that the command
```shell
echo "" | post4 ; echo $?
```
should print a nonzero value?

**Comment by SirWumpus** [comment]
> > should the program reach EOF (^D) then the exit status should be non-zero.
> 
> Do you mean that the command:
> 
> ```shell
> echo "" | post4 ; echo $?
> ```
> 
> should print a nonzero value?

No.  I'm think "clean" execution vs some exception occurring during the runtime.

```shell
elf$ printf ".( doing stuff) cr" | ./post4; echo $?
doing stuff
0
elf$ printf "' foo\n .( continue doing stuff) cr" | ./post4; echo $?

>> ' foo
>>      ^
-13 thrown: undefined word
continue doing stuff
3
elf$
```
