### ISSUE TITLE
Strange effect after pause (`ms`)

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#84]
When you enter something while Post4 is in pause, it does not receive your input.

```transcript
ok 1000 ms ( press <enter> three times )
ok 29;4R
```
After one second the cursor _unexpectedly_ moves to the upper-left corner of the window. If you then press Enter, the system says that "29;4R" is undefined. "29" is a line number, it may be different.

**Comment by SirWumpus** [comment]
> When you enter something while Post4 is in pause, it does not receive your input.

This is probably because input is handled in VMIN=1 VTIME=0, which disables ICANON that would buffer terminal input. 

> ```
> ok 1000 ms ( press <enter> three times )
> ok 29;4R
> ```
> 
> After one second the cursor _unexpectedly_ moves to the upper-left corner of the window. If you then

The repositioning is a little on the odd side.

>  press Enter, the system says that "29;4R" is undefined. "29" is a line number, it may be different.

That is the terminal response to the [alineGetRowCol()](https://github.com/SirWumpus/post4/blob/ef3b7845520ef5a8a7cf59b347ccb55dae20b34f/src/aline.c#L132) ANSI cursor position request.

**Comment by ruv** [comment]
> This is probably because input is handled in VMIN=1 VTIME=0, which disables ICANON that would buffer terminal input.

Interesting that a pressed key is buffered and available for `key`, but is not available for `accept`.
The phrase `1000 ms key .` prints the character for a key that was pressed while paused.

**Comment by SirWumpus** [comment]
> > This is probably because input is handled in VMIN=1 VTIME=0, which disables ICANON that would buffer terminal input.
> 
> Interesting that a pressed key is buffered and available for `key`, but is not available for `accept`. The phrase `1000 ms key .` prints the character for a key that was pressed while paused.

Well I was only hazarding a guess, before commit 8f806e03dd, which I think addresses the issues.
```
2000 ms s" PS2" env type pad dup /pad accept dup . cr type
```

The `TCSAFLUSH` will discard input, before accepting, which is best in order to ensure the ANSI cursor position request & response are processed correctly before input.  Using `TCSANOW` or `TCSADRAIN` results in the cursor jumping as type-ahead keys intermix with the ANSI cursor request/response.

Side-saddle: The cursor position is obtained from the terminal so as to know the current screen location after any prompts from which to redraw the input line while editing.

**Comment by SirWumpus** [comment]
I have tried and don't see how I can get buffered terminal input and line editing working together.  Probably have to completely rethink aline.c to do that.  For now the above appears to solve the odd behaviour.

**Comment by ruv** [comment]
> I have tried and don't see how I can get buffered terminal input and line editing working together.

The standard does not specify whether the input from the user input device is buffered while the system is paused. Some systems do buffering, some — not.
