### ISSUE TITLE
Newline LF vs CRLF on nixs?

### ISSUE THREAD

**Issue by SirWumpus** [SirWumpus/post4#92]
@ruv Up to now I've taken the view to always use CRLF newlines in output, cause it seems most portable across unixs and Windows (and probably MacOS).

But I was just playing with `eh(1)` and `vi(1)` (nvi not vim) filter `!` (bang) command to pipe input in/out through `post4` and it works just fine.  BUT the output in the editors shows the `^M` (CR) portion of the newline, because on unix only LF is treated as the newline.  Which is rather ugly to look at.

Should I have compile time option to select the type of newline?  And maybe a command-line option to change it?

**Comment by ruv** [comment]
> Up to now I've taken the view to always use CRLF newlines in output

The command:
```shell
echo 'cr cr bye' | post4 | hexdump
```
outputs:
```output
0000000 0a0d 0a0d
0000004
```
So, your `cr` actually uses LFCR in output 🙃   In contrast, the word `write-line` uses CRLF.

EOF is important when you are redirecting output to a file. An expected behavior is that a Forth system uses the line terminator sequence that is typical for the host OS.  I tested several systems on Linux — they all output single LF.

As an example, SP-Forth provides facilities for changing EOL at run-time, and can be configured to accept files in both LF and CRLF line endings.  The built-in initial value for EOL [is determined](https://github.com/rufig/spf4-utf8/blob/ab05ef34657d6f013ec0943b6c1513c2b4630c80/src/spf_compileoptions.f#L25-L31) by the EOL used in the source files in the working tree.  LF works well in both Windows and Linux terminals.

**Comment by SirWumpus** [comment]
> > Up to now I've taken the view to always use CRLF newlines in output
> 
> The command:
> 
> ```shell
> echo 'cr cr bye' | post4 | hexdump
> ```
> 
> outputs:
> 
> ```
> 0000000 0a0d 0a0d
> 0000004
> ```

WTF No way. I think your `hexdump` is using little-endian.

```shell
elf$ echo cr cr bye |./post4 |od -c
0000000   \r  \n  \r  \n
0000004
```


> So, your `cr` actually uses LFCR in output 🙃 In contrast, the word `write-line` uses CRLF.
>

Evil.  And no I don't use LFCR.  That's like using mixed tabs and spaces...

![wasntme](https://github.com/user-attachments/assets/17ab150b-8d18-451f-8f09-016726f52de9)

> EOF is important when you are redirecting output to a file. An expected behavior is that a Forth system uses the line terminator sequence that is typical for the host OS. I tested several systems on Linux — they all output single LF.

EOF?  

> As an example, SP-Forth provides facilities for changing EOL at run-time, and can be configured to accept files in both LF and CRLF line endings. The built-in initial value for EOL [is determined](https://github.com/rufig/spf4-utf8/blob/ab05ef34657d6f013ec0943b6c1513c2b4630c80/src/spf_compileoptions.f#L25-L31) by the EOL used in the source files in the working tree. LF works well in both Windows and Linux terminals.

LF in Windows is just a line feed (try CMD or PowerShell), some text editors handle it as newline, some do not; other non-interactive tools should be fine.  FreeDOS I'd expect wants/likes CRLF given its desire to clone DOS.

Anyway, I'm tweaking the source to deal with newlines (again (and I thought I was being clever with CRLF)).

**Comment by ruv** [comment]
> WTF No way. I think your `hexdump` is using little-endian.

You are right, my bad.  By default it outputs 16-bit numbers, not bytes.  But when I tested `write-line`, I used the option `-C`, so the output was per-byte.


> > EOF is important when you are redirecting output to a file. An expected behavior is that a Forth system uses the line terminator sequence that is typical for the host OS. I tested several systems on Linux — they all output single LF.
> 
> EOF?

Typo, I meant EOL (End Of Line).
